### ISSUE TITLE
扫描不到插件

### ISSUE THREAD

**Issue by yellowfish621** [Sakura7301/SimpleTimeTask#6]
![image](https://github.com/user-attachments/assets/9f1691ac-a661-4df0-b668-390202de2153)

**Comment by yellowfish621** [comment]
![image](https://github.com/user-attachments/assets/91dadde7-def3-49a7-bd0a-76520c3d21fa)
难道是这个原因？

**Comment by Sakura7301** [comment]
requirements.txt
你把这个文件的内容都注释掉再扫描一下应该就可以了，文件里面有提到一些模块是自带的，无需安装依赖。

**Comment by yellowfish621** [comment]
> requirements.txt 你把这个文件的内容都注释掉再扫描一下应该就可以了，文件里面有提到一些模块是自带的，无需安装依赖。

解决了，是服务器上同时装了两个版本python导致冲突

**Comment by Sakura7301** [comment]
嗯嗯好的
